version: '3'

services:
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build: '.'
    # command:  python ... # can be used to override the CMD in the dockerfile
    depends_on:
      - 'redis' # will launch redis first before web container
    # environment: # explicit stated
      # FLASK_DEBUG: true # explicit stated
    # or you could do the below in a file instead.
    env_file:
      - '.env'
    image: 'nickjj/web:1.0' # This uploads the image on run to repo
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'

volumes:
  redis: {} # needs to match the name on line 9, options would go in empty hash {}
